### ISSUE TITLE
Suggestion: `labels.coded` 

### ISSUE THREAD

**Issue by edwindj** [djvanderlaan/codelist#1]
`labels` is a generic function and it would make sense if a coded vector would support returning its labels using 
`labels.coded`

**Comment by djvanderlaan** [comment]
I think I would also like people to be able to use the package (at least part of it) without being forced to use the `coded` class. At moment people can call the `label` function without converting their object to `coded`. If we would switch from `label` to `labels` we would either have to supply both functions: `label` and `labels.coded` which is confusing. Or only `labels.coded` and people would have to call `labels.coded` directly (with the `.coded`) for non-coded objects. :thinking: 

Perhaps use `to_labels` next to `labels`. That would be less confusing...

**Comment by djvanderlaan** [comment]
In 1fe4511e50b5e998bf27a671993e57d0c4002df0 the `label` function has been removed and replaces by `labels.coded` and `tolabels`.
