### ISSUE TITLE
Naming cl* functions

### ISSUE THREAD

**Issue by edwindj** [djvanderlaan/codelist#2]
It's a matter of taste and convention, but currently some functions use the prefix `cl`, e.g. `cllevel`, `cllevels` etc.

Alternatives could be snake_case or camelCase e.g.`cl_level`, `cl_levels`.
Many R packages seem to use the snake_case variant nowadays.

**Comment by djvanderlaan** [comment]
For now I am sticking with the more compact notation (`clfilter`, `tolabels`) and only use underscores when necessary for readability.

**Comment by djvanderlaan** [comment]
Changed to `cl_` in commit 9f37424377d761fb97de4cbc73a423457a3973cf
