### ISSUE TITLE
Suggestion naming `clfilterlevel`

### ISSUE THREAD

**Issue by edwindj** [djvanderlaan/codelist#3]
The name `clfilterlevel` may be improved upon, what about the following alternatives?

- `filter_by_level`
- `select_level`
- `get_codes_of_level`

**Comment by djvanderlaan** [comment]
This function is now (of was) an internal function and has been renamed to `clfilter_by_level`. A new function `clfilter` has been introduced that allow filtering on both locale and hierarchical level. Functions operating on codelists now start with `cl` (without underscore).
