### ISSUE TITLE
Suggestions name `clfilterlocale`

### ISSUE THREAD

**Issue by edwindj** [djvanderlaan/codelist#4]
What about:

- `filter_by_locale`
- `select_locale`
-  `get_codes_of_locale`

**Comment by djvanderlaan** [comment]
This function is now (of was) an internal function and has been renamed to `clfilter_by_locale`. A new function `clfilter` has been introduced that allow filtering on both locale and hierarchical level. Functions operating on codelists now start with `cl` (without underscore).
