### ISSUE TITLE
Question: clfilterlocale missing codes?

### ISSUE THREAD

**Issue by edwindj** [djvanderlaan/codelist#5]
What happens if a code is missing in one locale but not in the others?
Should it be just left out?

**Comment by djvanderlaan** [comment]
I think `isvalidcodelist` should catch that and not accept the code list as valid. I can't think of valid reasons why this would be valid. As soon as you leave out one code, the meaning of the other codes change. 

Countries might use different codes ,for example, for educational levels as the educational systems are different. However, those are then different code lists and not translations of the same code list.

**Comment by djvanderlaan** [comment]
Created issue #8
